services:
  picoshare:
    build:
      context: .
    restart: unless-stopped
    environment:
      - PORT=${PORT:-4001}
      - PS_SHARED_SECRET=${PS_SHARED_SECRET}
      - PS_BEHIND_PROXY=${PS_BEHIND_PROXY:-true}
    command: -db /data/store.db
    volumes:
      - picoshare_data:/data

volumes:
  picoshare_data:
